common/build.gradle
Compile is deprated and should be replaced by implements:
https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle/44493811
And that is why  OperationAnnotatorTest is not working well with compile
=> change google-cloud-resourcemanager dependency from compile to implementation

common/src/main/resources/cloud_resources_uid.yaml, common/src/test/java/bio/terra/cloudres/resources/CloudResourceUidTest.java, google-storage/src/main/java/bio/terra/cloudres/google/storage/BlobCow.java, google-storage/src/main/java/bio/terra/cloudres/google/storage/SerializeUtils.java, google-storage/src/main/java/bio/terra/cloudres/google/storage/StorageCow.java, google-storage/src/test/java/bio/terra/cloudres/google/storage/BlobCowTest.java, google-storage/src/test/java/bio/terra/cloudres/google/storage/StorageCowTest.java
I'm a little unsure about whether to keep splitting out the recording into another test, or whether to add it to the existing test for the cow creation operations. Technically testing a diffeerent behavior, but there's not much to these tests and it's a fair amount of repetition as-is.
=> CA-868 Add cleanup recording for creating blobs in google storage.

google-bigquery/gradle.properties, google-bigquery/src/main/java/bio/terra/cloudres/google/bigquery/BigQueryCow.java, google-bigquery/src/test/java/bio/terra/cloudres/google/bigquery/BigQueryCowTest.java, google-bigquery/src/test/java/bio/terra/cloudres/google/bigquery/DatasetCowTest.java, google-bigquery/src/test/java/bio/terra/cloudres/google/bigquery/TableCowTest.java
Janitor needs this to delete/query dataset. But Janitor's Google Credential are in different project, so it needs the full DatasetId object which contains project id and dataset name. 
Also, change COW to return null if the cloud resource inside is null.
=> [PF-25] Add support to get and delete dataset by DatasetId instead string name

google-storage/src/test/java/bio/terra/cloudres/google/storage/BucketCowTest.java, google-storage/src/test/java/bio/terra/cloudres/google/storage/StorageCowTest.java, google-storage/src/test/java/bio/terra/cloudres/google/storage/StorageIntegrationUtils.java
It is recommanded from Broad InfoSecs that not to make cloud resource public.
=> [no ticket] make blob & bucket not public in test

google-iam/src/test/java/bio/terra/cloudres/google/iam/IamCowTest.java
Increase the time allowed for the SA to be deleted. This flaked out on me once. Hard to know what a good timeout is.
This is a test only change.
=> [no ticket] Try to make createAndListAndDeleteServiceAccount less flaky

.github/workflows/build-and-test.yaml, .github/workflows/publish.yml, README.md, build.gradle, common/src/testFixtures/java/bio/terra/cloudres/testing/IntegrationUtils.java, google-dns/src/test/java/bio/terra/cloudres/google/dns/DnsCowTest.java
These were a few cleanups coming out of my work on https://github.com/DataBiosphere/terra-cloud-resource-lib/pull/71.
=> [PF-571] Misc CI improvements: avoid duplicate unit tests, cache Gradle packages, run spotlessApply

cloud-resource-schema/gradle.properties, common/gradle.properties, google-api-services-common/gradle.properties, google-bigquery/gradle.properties, google-billing/gradle.properties, google-cloudresourcemanager/gradle.properties, google-compute/gradle.properties, google-dns/gradle.properties, google-iam/gradle.properties, google-notebooks/gradle.properties, google-serviceusage/gradle.properties, google-storage/gradle.properties
I forgot to check for this in #85. We haven't figured out a way to automate this on a per-package level yet, so we're still at manually modifying the `gradle.properties` files used to create the release version, which at least lets us increment the packages independently.
=> PF-744 Bump all the gradle.properties for PR #85.

build.gradle, google-storage/gradle.properties
I just published [google-storage](https://broadinstitute.jfrog.io/broadinstitute/libs-release-local/bio/terra/cloud-resource-lib/google-storage/0.12.0/) as 0.12.0 to make sure I didn't conflict with any existing versions. I think I skipped 0.11.0 in the process. Bumping it in gradle.properties to match reality.
=> bump version to match manual publish

azure-resourcemanager-compute/src/main/java/bio/terra/cloudres/azure/resourcemanager/compute/BaseRequestData.java, azure-resourcemanager-compute/src/main/java/bio/terra/cloudres/azure/resourcemanager/compute/ComputeManagerOperation.java, azure-resourcemanager-compute/src/main/java/bio/terra/cloudres/azure/resourcemanager/compute/CreatePublicIpRequestData.java, azure-resourcemanager-compute/src/main/java/bio/terra/cloudres/azure/resourcemanager/compute/DiskRequestData.java, azure-resourcemanager-compute/src/main/java/bio/terra/cloudres/azure/resourcemanager/compute/NetworkRequestData.java, azure-resourcemanager-compute/src/main/java/bio/terra/cloudres/azure/resourcemanager/compute/VMRequestData.java, azure-resourcemanager-compute/src/test/java/bio/terra/cloudres/azure/resourcemanager/compute/ComputeManagerCowTest.java
This is organized into the addition of 3 new models with a base model. It adds a test for disks and network in isolation, and a test to create all resources (IP, network, Disk), and then attach these resources to a vm. It's possible to create a VM with new resources too, but it seemed more logical to leverage the fact that the code for creating the components individually was already tested. 
Its worth noting this test creates a VM synchronously, which causes the tests to take ~4minutes. It's possible that we will want to handle this async in the application, which the azure SDK supports natively along with a built-in polling interface, but it made more sense to do it sync for the tests since verification is required and blocking before subsequent steps.
Note that this is not merging to …
=> [IA-2860] Azure models/tests for Network / Disk / VM resources CREATE / GET / DELETE

.github/workflows/build-and-test.yaml, render-test-config.sh
We changed the vault info since this was originally added. This should hopefully fix integration tests.
=> [no ticket] Fix typo in render-test-config.sh

buildSrc/build.gradle, google-bigquery/gradle.properties, google-bigquery/src/main/java/bio/terra/cloudres/google/bigquery/BigQueryCow.java, google-bigquery/src/test/java/bio/terra/cloudres/google/bigquery/BigQueryCowTest.java, platform/build.gradle, platform/gradle.properties
Before this PR, BigQueryCowTest.listDataset() failed 4-10 times out of 10. After this PR, passes 10/10.
=> Fix flakiness in BigQueryCowTest.listDataset()

azure-resourcemanager-common/gradle.lockfile, azure-resourcemanager-compute/gradle.lockfile, azure-resourcemanager-compute/gradle.properties, azure-resourcemanager-relay/gradle.properties, buildSrc/src/main/groovy/terra-cloud-resource-lib.library-conventions.gradle, common/gradle.lockfile, common/gradle.properties, google-api-services-common/gradle.lockfile, google-api-services-common/gradle.properties, google-bigquery/gradle.lockfile, google-bigquery/gradle.properties, google-billing/gradle.lockfile, google-billing/gradle.properties, google-cloudresourcemanager/gradle.lockfile, google-cloudresourcemanager/gradle.properties, google-compute/gradle.lockfile, google-compute/gradle.properties, google-dns/gradle.lockfile, google-dns/gradle.properties, google-iam/gradle.lockfile, google-iam/gradle.properties, google-notebooks/gradle.lockfile, google-notebooks/gradle.properties, google-serviceusage/gradle.lockfile, google-serviceusage/gradle.properties, google-storage/gradle.lockfile, google-storage/gradle.properties, platform/build.gradle, platform/gradle.properties
https://broadworkbench.atlassian.net/browse/TOAZ-37
* Bump janitor to the version that has https://github.com/DataBiosphere/terra-resource-janitor/pull/127
* Also reverted the previous PR that bumped all modules's patch version
* Bump Relay verison so that the new version uses new janitor
=> TOAZ-37 bump final janitor

azure-resourcemanager-relay/gradle.properties, azure-resourcemanager-relay/src/main/java/bio/terra/cloudres/azure/resourcemanager/relay/data/BaseRelayRequestData.java, azure-resourcemanager-relay/src/main/java/bio/terra/cloudres/azure/resourcemanager/relay/data/CreateRelayHybridConnectionRequestData.java, azure-resourcemanager-relay/src/main/java/bio/terra/cloudres/azure/resourcemanager/relay/data/CreateRelayRequestData.java, platform/gradle.properties
https://broadworkbench.atlassian.net/browse/TOAZ-71
region isn't required for hybrid connectioin since it lives inside a namespace, which is already region specific
=> [TOAZ-71] Remove region field for CreateRelayHybridConnectionRequestData

.github/workflows/tag-publish.yml
To fix error: `fatal: unsafe repository ('/github/workspace' is owned by someone else)`
=> [no ticket] Bump bumper to 0.0.6

.github/workflows/build-and-test.yml, .github/workflows/tag-publish.yml
The `joschi/setup-jdk@v2` Github action is deprecated and the recommendation is to move to the official github setup-java action with the `temurin` distribution: see https://github.com/joschi/setup-jdk#-notice
=> [PF-1731] Replace Java setup action

.github/workflows/build-and-test.yml
Only run PR checks when the PR targets primary/default branch
currently, all PRs (irrespective of the branch they target) automatically trigger PR checks. This is unnecessary and may cause the checks to be queued up on GitHub runner.
ref - 
- https://github.com/DataBiosphere/terra-workspace-manager/pull/1061
- https://broadworkbench.atlassian.net/browse/PF-2478
=> [PF-2478] Only run checks when PR targets default branch

src/main/java/bio/terra/cloudres/google/billing/CloudBillingClientCow.java, src/main/java/bio/terra/cloudres/google/billing/CloudBillingOperation.java, src/test/java/bio/terra/cloudres/google/billing/CloudBillingClientCowTest.java
Ticket: [WOR-714](https://broadworkbench.atlassian.net/browse/WOR-714)
BPM is using a snapshot from an [unmerged version of CRL](https://github.com/DataBiosphere/terra-cloud-resource-lib/pull/109). The unmerged PR was somewhat out of date wrt file organization. All I've done is cherry-pick the commits from the original PR onto the HEAD of the master branch and fix up the test. When this is merged, we'll update BPM to use the new version of CRL.
[WOR-714]: https://broadworkbench.atlassian.net/browse/WOR-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-714] add CloudBillingClient#testIamPermissions

.github/actions/bump-skip/action.yml, .github/workflows/build-and-test.yml, .github/workflows/tag-publish.yml
Replace deprecated commands in GH actions & workflows.
- use actions/setup-java@v3 instead of v2
- use actions/checkout@v3 instead of v2
- replace 'set-output' command
=> [TERRA-434] Replace deprecated commands in GH actions & workflows

build.gradle
Previously, we did not specify the platform or version number for several exported dependencies. As a result, clients which used CRL but did not pull in the GCP libraries BOM on their own (like RBS) would fail to properly resolve dependencies. This does not add any additional dependencies (so it has no lockfile changes).
Tested locally and with a throwaway published image using RBS dependencies
=> [PF-2630] Specify platform for api dependencies

src/main/java/bio/terra/cloudres/aws/console/ConsoleCow.java, src/main/java/bio/terra/cloudres/aws/console/ConsoleOperation.java, src/main/java/bio/terra/cloudres/aws/console/CrlConsoleException.java, src/test/java/bio/terra/cloudres/aws/console/ConsoleCowTest.java
AWS does not currently provide SDK calls in any language for federated console link generation.  This implements the processed described in [this AWS doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html), wrapped in COW instrumentation.
As per other AWS components, this provides unit test only, mocking all HTTP calls.
=> Add COW helper for building signed AWS Console links.

gradle/testing.gradle, src/main/java/bio/terra/cloudres/aws/bucket/S3BucketCow.java, src/main/java/bio/terra/cloudres/aws/bucket/S3BucketOperation.java, src/test/java/bio/terra/cloudres/aws/bucket/S3BucketCowTest.java
This is a small collection of improvements to the S3BucketCow as we've iterated on adding S3 buckets to WSM. The main changes:
- Add unchecked exceptions from the underlying S3 client to method signatures. This makes it clearer what exceptions these methods will throw in common failure modes
- Add a `folderExists` method as a wrapper around `listBlobs`
- Add a `deleteFolder` method which deletes multiple objects in a single call. This uses a different AWS endpoint, so I'm logging it as a different operation.
- Allow callers to pass tags in during object creation
- Fix `assertEquals` in tests, the expected and actual arguments were swapped.
In addition to the CRL tests, see [example WSM PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/1210) for a preview of how these …
=> [TERRA-498] Add folderExists and deleteFolder to s3BucketCow, surface errors

src/main/java/bio/terra/cloudres/aws/notebook/SageMakerNotebookCow.java, src/main/java/bio/terra/cloudres/aws/notebook/SageMakerNotebookOperation.java, src/test/java/bio/terra/cloudres/aws/notebook/SageMakerNotebookCowTest.java
Add method to get a presigned URL (equivalent to "proxy link" for Vertex AI instances, but signed rather than IAM-controlled).
=> Add notebook proxy signed URL creation to SageMaker Notebook COW.

src/test/java/bio/terra/cloudres/google/dataproc/DataprocCowTest.java
This configures the test dataproc clusters to automatically delete after 30m. This should help for when tests fail to clean up their clusters. Thanks Roger for thinking of this!
This also adds a `delete` call to the one test which created a cluster but did not delete it.
=> [PF2868] Add autodelete to test clusters

src/main/java/bio/terra/cloudres/google/billing/CloudBillingClientCow.java, src/main/java/bio/terra/cloudres/google/billing/SerializeBillingUtils.java, src/main/java/bio/terra/cloudres/google/storage/SerializeUtils.java, src/main/java/bio/terra/cloudres/util/SerializeHelper.java, src/test/java/bio/terra/cloudres/google/billing/CloudBillingClientCowTest.java
Ticket: https://broadworkbench.atlassian.net/browse/CORE-117
**Context:**
When attempting to update RBS to the latest terra-common-lib, the tests failed because gson cannot serialize the project billing info:
```
com.google.gson.JsonIOException: Failed making field 'java.lang.ref.Reference#referent' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type. See https://github.com/google/gson/blob/main/Troubleshooting.md#reflection-inaccessible
```
**Changes:**
Use the custom type adapter added in https://github.com/DataBiosphere/terra-cloud-resource-lib/pull/179
=> [CORE-117] Fix google billing GSON serialization

src/main/java/bio/terra/cloudres/google/billing/SerializeBillingUtils.java, src/test/java/bio/terra/cloudres/google/billing/CloudBillingClientCowTest.java
Explicitly define each field in the project billing info JSON object instead of relying on GSON for serialization.
=> [CORE-117] Do not use gson to serialize ProjectBillingInfo

.gitignore
In order to complete https://broadworkbench.atlassian.net/browse/CORE-593, service account auth will need to be added.  Preemptively updating .gitignore to avoid committing any creds.  Actual PR for CORE-593 will come later
=> [CORE-593] Update gitignore
